-- Phase 1 extension: add full flattened AirportFlightContract field coverage as queryable columns.
-- raw_payload remains the source of truth; these columns are denormalized access paths.

alter table public.raw_flights
  add column if not exists with_location boolean,

  -- movement.*
  add column if not exists movement_airport_icao text,
  add column if not exists movement_airport_iata text,
  add column if not exists movement_airport_local_code text,
  add column if not exists movement_airport_name text,
  add column if not exists movement_airport_short_name text,
  add column if not exists movement_airport_municipality_name text,
  add column if not exists movement_airport_location_lat double precision,
  add column if not exists movement_airport_location_lon double precision,
  add column if not exists movement_airport_country_code text,
  add column if not exists movement_airport_time_zone text,
  add column if not exists movement_scheduled_time_utc timestamptz,
  add column if not exists movement_scheduled_time_local timestamp without time zone,
  add column if not exists movement_revised_time_utc timestamptz,
  add column if not exists movement_revised_time_local timestamp without time zone,
  add column if not exists movement_predicted_time_utc timestamptz,
  add column if not exists movement_predicted_time_local timestamp without time zone,
  add column if not exists movement_runway_time_utc timestamptz,
  add column if not exists movement_runway_time_local timestamp without time zone,
  add column if not exists movement_terminal text,
  add column if not exists movement_check_in_desk text,
  add column if not exists movement_gate text,
  add column if not exists movement_baggage_belt text,
  add column if not exists movement_runway text,
  add column if not exists movement_quality text[],

  -- departure.*
  add column if not exists departure_airport_icao text,
  add column if not exists departure_airport_iata text,
  add column if not exists departure_airport_local_code text,
  add column if not exists departure_airport_name text,
  add column if not exists departure_airport_short_name text,
  add column if not exists departure_airport_municipality_name text,
  add column if not exists departure_airport_location_lat double precision,
  add column if not exists departure_airport_location_lon double precision,
  add column if not exists departure_airport_country_code text,
  add column if not exists departure_airport_time_zone text,
  add column if not exists departure_revised_time_local timestamp without time zone,
  add column if not exists departure_predicted_time_local timestamp without time zone,
  add column if not exists departure_runway_time_local timestamp without time zone,
  add column if not exists departure_check_in_desk text,
  add column if not exists departure_baggage_belt text,
  add column if not exists departure_runway text,
  add column if not exists departure_quality text[],

  -- arrival.*
  add column if not exists arrival_airport_icao text,
  add column if not exists arrival_airport_local_code text,
  add column if not exists arrival_airport_name text,
  add column if not exists arrival_airport_short_name text,
  add column if not exists arrival_airport_municipality_name text,
  add column if not exists arrival_airport_location_lat double precision,
  add column if not exists arrival_airport_location_lon double precision,
  add column if not exists arrival_airport_country_code text,
  add column if not exists arrival_airport_time_zone text,
  add column if not exists arrival_scheduled_time_local timestamp without time zone,
  add column if not exists arrival_revised_time_local timestamp without time zone,
  add column if not exists arrival_predicted_time_local timestamp without time zone,
  add column if not exists arrival_runway_time_local timestamp without time zone,
  add column if not exists arrival_terminal text,
  add column if not exists arrival_check_in_desk text,
  add column if not exists arrival_gate text,
  add column if not exists arrival_baggage_belt text,
  add column if not exists arrival_runway text,
  add column if not exists arrival_quality text[],

  -- airline.*
  add column if not exists airline_name text,

  -- aircraft.*
  add column if not exists aircraft_mode_s text,
  add column if not exists aircraft_image_url text,
  add column if not exists aircraft_image_web_url text,
  add column if not exists aircraft_image_author text,
  add column if not exists aircraft_image_title text,
  add column if not exists aircraft_image_description text,
  add column if not exists aircraft_image_license text,
  add column if not exists aircraft_image_html_attributions text[],

  -- location.*
  add column if not exists location_pressure_altitude_meter double precision,
  add column if not exists location_pressure_altitude_km double precision,
  add column if not exists location_pressure_altitude_mile double precision,
  add column if not exists location_pressure_altitude_nm double precision,
  add column if not exists location_pressure_altitude_feet double precision,
  add column if not exists location_altitude_meter double precision,
  add column if not exists location_altitude_km double precision,
  add column if not exists location_altitude_mile double precision,
  add column if not exists location_altitude_nm double precision,
  add column if not exists location_altitude_feet double precision,
  add column if not exists location_pressure_hpa double precision,
  add column if not exists location_pressure_in_hg double precision,
  add column if not exists location_pressure_mm_hg double precision,
  add column if not exists location_ground_speed_kt double precision,
  add column if not exists location_ground_speed_km_per_hour double precision,
  add column if not exists location_ground_speed_mi_per_hour double precision,
  add column if not exists location_ground_speed_meter_per_second double precision,
  add column if not exists location_true_track_deg double precision,
  add column if not exists location_true_track_rad double precision,
  add column if not exists location_vsi_fpm integer;
